# Generated by Django 5.2.12 on 2026-03-26 02:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, help_text='Origin breeder or country of this bloodline', max_length=100)),
                ('is_predefined', models.BooleanField(default=False, help_text='System-seeded bloodline (cannot be deleted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bloodlines', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Bloodline',
                'verbose_name_plural': 'Bloodlines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gamefowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wing_band', models.CharField(blank=True, help_text='Unique wing band ID for identification', max_length=50)),
                ('breed', models.CharField(blank=True, help_text='General breed classification', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Stag/Cock'), ('female', 'Pullet/Hen')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('breeding', 'Breeding'), ('retired', 'Retired'), ('deceased', 'Deceased'), ('sold', 'Sold')], default='active', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('leg_color', models.CharField(blank=True, max_length=50)),
                ('plumage_color', models.CharField(blank=True, max_length=100)),
                ('plumage_pattern', models.CharField(blank=True, max_length=100)),
                ('eye_color', models.CharField(blank=True, max_length=50)),
                ('comb_type', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fowl/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dam', models.ForeignKey(blank=True, help_text='Mother (must be female)', limit_choices_to={'gender': 'female'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_offspring', to='fowl.gamefowl')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fowls', to='accounts.userprofile')),
                ('sire', models.ForeignKey(blank=True, help_text='Father (must be male)', limit_choices_to={'gender': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sire_offspring', to='fowl.gamefowl')),
            ],
            options={
                'verbose_name': 'Gamefowl',
                'verbose_name_plural': 'Gamefowl',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FowlBloodline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of this bloodline (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_manual_override', models.BooleanField(default=False, help_text='True if user manually set this, bypassing auto-calculation')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('bloodline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fowl_percentages', to='fowl.bloodline')),
                ('fowl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloodline_percentages', to='fowl.gamefowl')),
            ],
            options={
                'verbose_name': 'Fowl Bloodline',
                'verbose_name_plural': 'Fowl Bloodlines',
                'ordering': ['-percentage'],
                'unique_together': {('fowl', 'bloodline')},
            },
        ),
    ]
