# Generated by Django 5.2.12 on 2026-03-26 02:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fowl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, help_text='Name of the derby or event', max_length=200)),
                ('arena_name', models.CharField(max_length=200)),
                ('arena_location', models.CharField(blank=True, max_length=300)),
                ('scheduled_datetime', models.DateTimeField()),
                ('opponent_name', models.CharField(blank=True, help_text='Opponent fowl name or owner', max_length=100)),
                ('opponent_breed', models.CharField(blank=True, max_length=100)),
                ('opponent_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Opponent weight in kg', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw'), ('no_contest', 'No Contest')], max_length=20)),
                ('fight_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration of fight in minutes', null=True)),
                ('notes', models.TextField(blank=True, help_text='Fight notes, observations, performance details')),
                ('fowl_weight_at_fight', models.DecimalField(blank=True, decimal_places=2, help_text="Fowl's weight at time of fight in kg", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the fight result was recorded', null=True)),
                ('fowl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='fowl.gamefowl')),
            ],
            options={
                'verbose_name': 'Fight',
                'verbose_name_plural': 'Fights',
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
